twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        categories: '@App\Service\CategoryService'
        services: '@App\Service\ServiceService'

when@test:
    twig:
        strict_variables: true
